export enum ConfigurationKeys {
  DATABASE_HOST = "DOC_DB_HOST",
  DATABASE_USERNAME = "DOC_DB_USER",
  DATABASE_PASSWORD = "DOC_DB_PASSWORD",
  DATABASE_NAME = "DOC_DB_NAME",
  MULTER_DEST = "DOC_FILE_DEST",
  DATABASE_TYPE = "DOC_DB_TYPE",
}
